version: '3.8'
# VIRTUAL_HOST
# VIRTUAL_PORT
# LETSENCRYPT_HOST

services:
  
  phpmyadmin:
    image: phpmyadmin:5.1.3
    restart: on-failure
    environment:
      - VIRTUAL_HOST=phpmyadmin.gastrocrm.online
      - LETSENCRYPT_HOST=phpmyadmin.gastrocrm.online
      - PMA_HOST=mariadb
      - HIDE_PHP_VERSION=true
    networks:
      - default
      - nginx-proxy

  mariadb:
    image: mariadb:10.7.3
    restart: on-failure
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - .env.secret
    environment:
      - LANG=C.UTF-8
    ports:
      - 9909:3306
    volumes:
     - mariadb-volume:/var/lib/mysql

  nginx:
    image: nginx:alpine
    restart: on-failure
    environment:
      - VIRTUAL_HOST=gastrocrm.online
      - LETSENCRYPT_HOST=gastrocrm.online
    depends_on:
      - gastrocrm_backend
      - gastrocrm_frontend
    networks:
      - default
      - nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  gastrocrm_backend:
    image: srozdzynski/gastrocrm
    restart: on-failure
    env_file:
      - .env.secret
    depends_on:
      - mariadb

  gastrocrm_frontend:
    image: srozdzynski/gastrocrm-frontend
    restart: on-failure
    depends_on:
      - gastrocrm_backend
      
networks:
  nginx-proxy:
    external: true

volumes:
  mariadb-volume:
